version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ethers
    versions:
    - 5.0.26
    - 5.0.27
    - 5.0.28
    - 5.0.29
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.3
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
